/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-06-26 at 00:09:35 UTC 
 * Modify at your own risk.
 */

package com.conexion.entidades.viajeendpoint;

/**
 * Service definition for Viajeendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ViajeendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Viajeendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the viajeendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://fletemadera.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "viajeendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Viajeendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Viajeendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getViaje".
   *
   * This request holds the parameters needed by the viajeendpoint server.  After setting any optional
   * parameters, call the {@link GetViaje#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetViaje getViaje(java.lang.Long id) throws java.io.IOException {
    GetViaje result = new GetViaje(id);
    initialize(result);
    return result;
  }

  public class GetViaje extends ViajeendpointRequest<com.conexion.entidades.viajeendpoint.model.Viaje> {

    private static final String REST_PATH = "viaje/{id}";

    /**
     * Create a request for the method "getViaje".
     *
     * This request holds the parameters needed by the the viajeendpoint server.  After setting any
     * optional parameters, call the {@link GetViaje#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetViaje#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetViaje(java.lang.Long id) {
      super(Viajeendpoint.this, "GET", REST_PATH, null, com.conexion.entidades.viajeendpoint.model.Viaje.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetViaje setAlt(java.lang.String alt) {
      return (GetViaje) super.setAlt(alt);
    }

    @Override
    public GetViaje setFields(java.lang.String fields) {
      return (GetViaje) super.setFields(fields);
    }

    @Override
    public GetViaje setKey(java.lang.String key) {
      return (GetViaje) super.setKey(key);
    }

    @Override
    public GetViaje setOauthToken(java.lang.String oauthToken) {
      return (GetViaje) super.setOauthToken(oauthToken);
    }

    @Override
    public GetViaje setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetViaje) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetViaje setQuotaUser(java.lang.String quotaUser) {
      return (GetViaje) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetViaje setUserIp(java.lang.String userIp) {
      return (GetViaje) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetViaje setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetViaje set(String parameterName, Object value) {
      return (GetViaje) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertViaje".
   *
   * This request holds the parameters needed by the viajeendpoint server.  After setting any optional
   * parameters, call the {@link InsertViaje#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.conexion.entidades.viajeendpoint.model.Viaje}
   * @return the request
   */
  public InsertViaje insertViaje(com.conexion.entidades.viajeendpoint.model.Viaje content) throws java.io.IOException {
    InsertViaje result = new InsertViaje(content);
    initialize(result);
    return result;
  }

  public class InsertViaje extends ViajeendpointRequest<com.conexion.entidades.viajeendpoint.model.Viaje> {

    private static final String REST_PATH = "viaje";

    /**
     * Create a request for the method "insertViaje".
     *
     * This request holds the parameters needed by the the viajeendpoint server.  After setting any
     * optional parameters, call the {@link InsertViaje#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertViaje#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.conexion.entidades.viajeendpoint.model.Viaje}
     * @since 1.13
     */
    protected InsertViaje(com.conexion.entidades.viajeendpoint.model.Viaje content) {
      super(Viajeendpoint.this, "POST", REST_PATH, content, com.conexion.entidades.viajeendpoint.model.Viaje.class);
    }

    @Override
    public InsertViaje setAlt(java.lang.String alt) {
      return (InsertViaje) super.setAlt(alt);
    }

    @Override
    public InsertViaje setFields(java.lang.String fields) {
      return (InsertViaje) super.setFields(fields);
    }

    @Override
    public InsertViaje setKey(java.lang.String key) {
      return (InsertViaje) super.setKey(key);
    }

    @Override
    public InsertViaje setOauthToken(java.lang.String oauthToken) {
      return (InsertViaje) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertViaje setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertViaje) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertViaje setQuotaUser(java.lang.String quotaUser) {
      return (InsertViaje) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertViaje setUserIp(java.lang.String userIp) {
      return (InsertViaje) super.setUserIp(userIp);
    }

    @Override
    public InsertViaje set(String parameterName, Object value) {
      return (InsertViaje) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listViaje".
   *
   * This request holds the parameters needed by the viajeendpoint server.  After setting any optional
   * parameters, call the {@link ListViaje#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListViaje listViaje() throws java.io.IOException {
    ListViaje result = new ListViaje();
    initialize(result);
    return result;
  }

  public class ListViaje extends ViajeendpointRequest<com.conexion.entidades.viajeendpoint.model.CollectionResponseViaje> {

    private static final String REST_PATH = "viaje";

    /**
     * Create a request for the method "listViaje".
     *
     * This request holds the parameters needed by the the viajeendpoint server.  After setting any
     * optional parameters, call the {@link ListViaje#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListViaje#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListViaje() {
      super(Viajeendpoint.this, "GET", REST_PATH, null, com.conexion.entidades.viajeendpoint.model.CollectionResponseViaje.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListViaje setAlt(java.lang.String alt) {
      return (ListViaje) super.setAlt(alt);
    }

    @Override
    public ListViaje setFields(java.lang.String fields) {
      return (ListViaje) super.setFields(fields);
    }

    @Override
    public ListViaje setKey(java.lang.String key) {
      return (ListViaje) super.setKey(key);
    }

    @Override
    public ListViaje setOauthToken(java.lang.String oauthToken) {
      return (ListViaje) super.setOauthToken(oauthToken);
    }

    @Override
    public ListViaje setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListViaje) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListViaje setQuotaUser(java.lang.String quotaUser) {
      return (ListViaje) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListViaje setUserIp(java.lang.String userIp) {
      return (ListViaje) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListViaje setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListViaje setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListViaje set(String parameterName, Object value) {
      return (ListViaje) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "modificarFechaDePagoMontoCuentaCorrienteDESTINO".
   *
   * This request holds the parameters needed by the viajeendpoint server.  After setting any optional
   * parameters, call the {@link ModificarFechaDePagoMontoCuentaCorrienteDESTINO#execute()} method to
   * invoke the remote operation.
   *
   * @param id
   * @param fechaPagarFlete
   * @param pagoFlete
   * @return the request
   */
  public ModificarFechaDePagoMontoCuentaCorrienteDESTINO modificarFechaDePagoMontoCuentaCorrienteDESTINO(java.lang.Long id, java.lang.String fechaPagarFlete, java.lang.String pagoFlete) throws java.io.IOException {
    ModificarFechaDePagoMontoCuentaCorrienteDESTINO result = new ModificarFechaDePagoMontoCuentaCorrienteDESTINO(id, fechaPagarFlete, pagoFlete);
    initialize(result);
    return result;
  }

  public class ModificarFechaDePagoMontoCuentaCorrienteDESTINO extends ViajeendpointRequest<Void> {

    private static final String REST_PATH = "modificarFechaDePagoMontoCuentaCorrienteDESTINO/{id}/{fechaPagar_flete}/{pago_flete}";

    /**
     * Create a request for the method "modificarFechaDePagoMontoCuentaCorrienteDESTINO".
     *
     * This request holds the parameters needed by the the viajeendpoint server.  After setting any
     * optional parameters, call the {@link ModificarFechaDePagoMontoCuentaCorrienteDESTINO#execute()}
     * method to invoke the remote operation. <p> {@link ModificarFechaDePagoMontoCuentaCorrienteDESTI
     * NO#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must be
     * called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @param fechaPagarFlete
     * @param pagoFlete
     * @since 1.13
     */
    protected ModificarFechaDePagoMontoCuentaCorrienteDESTINO(java.lang.Long id, java.lang.String fechaPagarFlete, java.lang.String pagoFlete) {
      super(Viajeendpoint.this, "POST", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      this.fechaPagarFlete = com.google.api.client.util.Preconditions.checkNotNull(fechaPagarFlete, "Required parameter fechaPagarFlete must be specified.");
      this.pagoFlete = com.google.api.client.util.Preconditions.checkNotNull(pagoFlete, "Required parameter pagoFlete must be specified.");
    }

    @Override
    public ModificarFechaDePagoMontoCuentaCorrienteDESTINO setAlt(java.lang.String alt) {
      return (ModificarFechaDePagoMontoCuentaCorrienteDESTINO) super.setAlt(alt);
    }

    @Override
    public ModificarFechaDePagoMontoCuentaCorrienteDESTINO setFields(java.lang.String fields) {
      return (ModificarFechaDePagoMontoCuentaCorrienteDESTINO) super.setFields(fields);
    }

    @Override
    public ModificarFechaDePagoMontoCuentaCorrienteDESTINO setKey(java.lang.String key) {
      return (ModificarFechaDePagoMontoCuentaCorrienteDESTINO) super.setKey(key);
    }

    @Override
    public ModificarFechaDePagoMontoCuentaCorrienteDESTINO setOauthToken(java.lang.String oauthToken) {
      return (ModificarFechaDePagoMontoCuentaCorrienteDESTINO) super.setOauthToken(oauthToken);
    }

    @Override
    public ModificarFechaDePagoMontoCuentaCorrienteDESTINO setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ModificarFechaDePagoMontoCuentaCorrienteDESTINO) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ModificarFechaDePagoMontoCuentaCorrienteDESTINO setQuotaUser(java.lang.String quotaUser) {
      return (ModificarFechaDePagoMontoCuentaCorrienteDESTINO) super.setQuotaUser(quotaUser);
    }

    @Override
    public ModificarFechaDePagoMontoCuentaCorrienteDESTINO setUserIp(java.lang.String userIp) {
      return (ModificarFechaDePagoMontoCuentaCorrienteDESTINO) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public ModificarFechaDePagoMontoCuentaCorrienteDESTINO setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @com.google.api.client.util.Key("fechaPagar_flete")
    private java.lang.String fechaPagarFlete;

    /**

     */
    public java.lang.String getFechaPagarFlete() {
      return fechaPagarFlete;
    }

    public ModificarFechaDePagoMontoCuentaCorrienteDESTINO setFechaPagarFlete(java.lang.String fechaPagarFlete) {
      this.fechaPagarFlete = fechaPagarFlete;
      return this;
    }

    @com.google.api.client.util.Key("pago_flete")
    private java.lang.String pagoFlete;

    /**

     */
    public java.lang.String getPagoFlete() {
      return pagoFlete;
    }

    public ModificarFechaDePagoMontoCuentaCorrienteDESTINO setPagoFlete(java.lang.String pagoFlete) {
      this.pagoFlete = pagoFlete;
      return this;
    }

    @Override
    public ModificarFechaDePagoMontoCuentaCorrienteDESTINO set(String parameterName, Object value) {
      return (ModificarFechaDePagoMontoCuentaCorrienteDESTINO) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "modificarFechaDePagoMontoCuentaCorrienteORIGEN".
   *
   * This request holds the parameters needed by the viajeendpoint server.  After setting any optional
   * parameters, call the {@link ModificarFechaDePagoMontoCuentaCorrienteORIGEN#execute()} method to
   * invoke the remote operation.
   *
   * @param id
   * @param fechaPagarOrigen
   * @param pago
   * @param kilosOrigenReales
   * @return the request
   */
  public ModificarFechaDePagoMontoCuentaCorrienteORIGEN modificarFechaDePagoMontoCuentaCorrienteORIGEN(java.lang.Long id, java.lang.String fechaPagarOrigen, java.lang.String pago, java.lang.String kilosOrigenReales) throws java.io.IOException {
    ModificarFechaDePagoMontoCuentaCorrienteORIGEN result = new ModificarFechaDePagoMontoCuentaCorrienteORIGEN(id, fechaPagarOrigen, pago, kilosOrigenReales);
    initialize(result);
    return result;
  }

  public class ModificarFechaDePagoMontoCuentaCorrienteORIGEN extends ViajeendpointRequest<Void> {

    private static final String REST_PATH = "modificarFechaDePagoMontoCuentaCorrienteORIGEN/{id}/{fechaPagar_origen}/{pago}/{kilosOrigenReales}";

    /**
     * Create a request for the method "modificarFechaDePagoMontoCuentaCorrienteORIGEN".
     *
     * This request holds the parameters needed by the the viajeendpoint server.  After setting any
     * optional parameters, call the {@link ModificarFechaDePagoMontoCuentaCorrienteORIGEN#execute()}
     * method to invoke the remote operation. <p> {@link ModificarFechaDePagoMontoCuentaCorrienteORIGE
     * N#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must be
     * called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @param fechaPagarOrigen
     * @param pago
     * @param kilosOrigenReales
     * @since 1.13
     */
    protected ModificarFechaDePagoMontoCuentaCorrienteORIGEN(java.lang.Long id, java.lang.String fechaPagarOrigen, java.lang.String pago, java.lang.String kilosOrigenReales) {
      super(Viajeendpoint.this, "POST", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      this.fechaPagarOrigen = com.google.api.client.util.Preconditions.checkNotNull(fechaPagarOrigen, "Required parameter fechaPagarOrigen must be specified.");
      this.pago = com.google.api.client.util.Preconditions.checkNotNull(pago, "Required parameter pago must be specified.");
      this.kilosOrigenReales = com.google.api.client.util.Preconditions.checkNotNull(kilosOrigenReales, "Required parameter kilosOrigenReales must be specified.");
    }

    @Override
    public ModificarFechaDePagoMontoCuentaCorrienteORIGEN setAlt(java.lang.String alt) {
      return (ModificarFechaDePagoMontoCuentaCorrienteORIGEN) super.setAlt(alt);
    }

    @Override
    public ModificarFechaDePagoMontoCuentaCorrienteORIGEN setFields(java.lang.String fields) {
      return (ModificarFechaDePagoMontoCuentaCorrienteORIGEN) super.setFields(fields);
    }

    @Override
    public ModificarFechaDePagoMontoCuentaCorrienteORIGEN setKey(java.lang.String key) {
      return (ModificarFechaDePagoMontoCuentaCorrienteORIGEN) super.setKey(key);
    }

    @Override
    public ModificarFechaDePagoMontoCuentaCorrienteORIGEN setOauthToken(java.lang.String oauthToken) {
      return (ModificarFechaDePagoMontoCuentaCorrienteORIGEN) super.setOauthToken(oauthToken);
    }

    @Override
    public ModificarFechaDePagoMontoCuentaCorrienteORIGEN setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ModificarFechaDePagoMontoCuentaCorrienteORIGEN) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ModificarFechaDePagoMontoCuentaCorrienteORIGEN setQuotaUser(java.lang.String quotaUser) {
      return (ModificarFechaDePagoMontoCuentaCorrienteORIGEN) super.setQuotaUser(quotaUser);
    }

    @Override
    public ModificarFechaDePagoMontoCuentaCorrienteORIGEN setUserIp(java.lang.String userIp) {
      return (ModificarFechaDePagoMontoCuentaCorrienteORIGEN) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public ModificarFechaDePagoMontoCuentaCorrienteORIGEN setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @com.google.api.client.util.Key("fechaPagar_origen")
    private java.lang.String fechaPagarOrigen;

    /**

     */
    public java.lang.String getFechaPagarOrigen() {
      return fechaPagarOrigen;
    }

    public ModificarFechaDePagoMontoCuentaCorrienteORIGEN setFechaPagarOrigen(java.lang.String fechaPagarOrigen) {
      this.fechaPagarOrigen = fechaPagarOrigen;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String pago;

    /**

     */
    public java.lang.String getPago() {
      return pago;
    }

    public ModificarFechaDePagoMontoCuentaCorrienteORIGEN setPago(java.lang.String pago) {
      this.pago = pago;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String kilosOrigenReales;

    /**

     */
    public java.lang.String getKilosOrigenReales() {
      return kilosOrigenReales;
    }

    public ModificarFechaDePagoMontoCuentaCorrienteORIGEN setKilosOrigenReales(java.lang.String kilosOrigenReales) {
      this.kilosOrigenReales = kilosOrigenReales;
      return this;
    }

    @Override
    public ModificarFechaDePagoMontoCuentaCorrienteORIGEN set(String parameterName, Object value) {
      return (ModificarFechaDePagoMontoCuentaCorrienteORIGEN) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "obtenerMaxId".
   *
   * This request holds the parameters needed by the viajeendpoint server.  After setting any optional
   * parameters, call the {@link ObtenerMaxId#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ObtenerMaxId obtenerMaxId() throws java.io.IOException {
    ObtenerMaxId result = new ObtenerMaxId();
    initialize(result);
    return result;
  }

  public class ObtenerMaxId extends ViajeendpointRequest<com.conexion.entidades.viajeendpoint.model.Viaje> {

    private static final String REST_PATH = "obtenerMaxId";

    /**
     * Create a request for the method "obtenerMaxId".
     *
     * This request holds the parameters needed by the the viajeendpoint server.  After setting any
     * optional parameters, call the {@link ObtenerMaxId#execute()} method to invoke the remote
     * operation. <p> {@link
     * ObtenerMaxId#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ObtenerMaxId() {
      super(Viajeendpoint.this, "POST", REST_PATH, null, com.conexion.entidades.viajeendpoint.model.Viaje.class);
    }

    @Override
    public ObtenerMaxId setAlt(java.lang.String alt) {
      return (ObtenerMaxId) super.setAlt(alt);
    }

    @Override
    public ObtenerMaxId setFields(java.lang.String fields) {
      return (ObtenerMaxId) super.setFields(fields);
    }

    @Override
    public ObtenerMaxId setKey(java.lang.String key) {
      return (ObtenerMaxId) super.setKey(key);
    }

    @Override
    public ObtenerMaxId setOauthToken(java.lang.String oauthToken) {
      return (ObtenerMaxId) super.setOauthToken(oauthToken);
    }

    @Override
    public ObtenerMaxId setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ObtenerMaxId) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ObtenerMaxId setQuotaUser(java.lang.String quotaUser) {
      return (ObtenerMaxId) super.setQuotaUser(quotaUser);
    }

    @Override
    public ObtenerMaxId setUserIp(java.lang.String userIp) {
      return (ObtenerMaxId) super.setUserIp(userIp);
    }

    @Override
    public ObtenerMaxId set(String parameterName, Object value) {
      return (ObtenerMaxId) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "obtenerViajesCargaPendiente".
   *
   * This request holds the parameters needed by the viajeendpoint server.  After setting any optional
   * parameters, call the {@link ObtenerViajesCargaPendiente#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ObtenerViajesCargaPendiente obtenerViajesCargaPendiente() throws java.io.IOException {
    ObtenerViajesCargaPendiente result = new ObtenerViajesCargaPendiente();
    initialize(result);
    return result;
  }

  public class ObtenerViajesCargaPendiente extends ViajeendpointRequest<com.conexion.entidades.viajeendpoint.model.ViajeCollection> {

    private static final String REST_PATH = "obtenerViajesCargaPendiente";

    /**
     * Create a request for the method "obtenerViajesCargaPendiente".
     *
     * This request holds the parameters needed by the the viajeendpoint server.  After setting any
     * optional parameters, call the {@link ObtenerViajesCargaPendiente#execute()} method to invoke
     * the remote operation. <p> {@link ObtenerViajesCargaPendiente#initialize(com.google.api.client.g
     * oogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ObtenerViajesCargaPendiente() {
      super(Viajeendpoint.this, "POST", REST_PATH, null, com.conexion.entidades.viajeendpoint.model.ViajeCollection.class);
    }

    @Override
    public ObtenerViajesCargaPendiente setAlt(java.lang.String alt) {
      return (ObtenerViajesCargaPendiente) super.setAlt(alt);
    }

    @Override
    public ObtenerViajesCargaPendiente setFields(java.lang.String fields) {
      return (ObtenerViajesCargaPendiente) super.setFields(fields);
    }

    @Override
    public ObtenerViajesCargaPendiente setKey(java.lang.String key) {
      return (ObtenerViajesCargaPendiente) super.setKey(key);
    }

    @Override
    public ObtenerViajesCargaPendiente setOauthToken(java.lang.String oauthToken) {
      return (ObtenerViajesCargaPendiente) super.setOauthToken(oauthToken);
    }

    @Override
    public ObtenerViajesCargaPendiente setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ObtenerViajesCargaPendiente) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ObtenerViajesCargaPendiente setQuotaUser(java.lang.String quotaUser) {
      return (ObtenerViajesCargaPendiente) super.setQuotaUser(quotaUser);
    }

    @Override
    public ObtenerViajesCargaPendiente setUserIp(java.lang.String userIp) {
      return (ObtenerViajesCargaPendiente) super.setUserIp(userIp);
    }

    @Override
    public ObtenerViajesCargaPendiente set(String parameterName, Object value) {
      return (ObtenerViajesCargaPendiente) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "obtenerViajesDescargaPendiente".
   *
   * This request holds the parameters needed by the viajeendpoint server.  After setting any optional
   * parameters, call the {@link ObtenerViajesDescargaPendiente#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ObtenerViajesDescargaPendiente obtenerViajesDescargaPendiente() throws java.io.IOException {
    ObtenerViajesDescargaPendiente result = new ObtenerViajesDescargaPendiente();
    initialize(result);
    return result;
  }

  public class ObtenerViajesDescargaPendiente extends ViajeendpointRequest<com.conexion.entidades.viajeendpoint.model.ViajeCollection> {

    private static final String REST_PATH = "obtenerViajesDescargaPendiente";

    /**
     * Create a request for the method "obtenerViajesDescargaPendiente".
     *
     * This request holds the parameters needed by the the viajeendpoint server.  After setting any
     * optional parameters, call the {@link ObtenerViajesDescargaPendiente#execute()} method to invoke
     * the remote operation. <p> {@link ObtenerViajesDescargaPendiente#initialize(com.google.api.clien
     * t.googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ObtenerViajesDescargaPendiente() {
      super(Viajeendpoint.this, "POST", REST_PATH, null, com.conexion.entidades.viajeendpoint.model.ViajeCollection.class);
    }

    @Override
    public ObtenerViajesDescargaPendiente setAlt(java.lang.String alt) {
      return (ObtenerViajesDescargaPendiente) super.setAlt(alt);
    }

    @Override
    public ObtenerViajesDescargaPendiente setFields(java.lang.String fields) {
      return (ObtenerViajesDescargaPendiente) super.setFields(fields);
    }

    @Override
    public ObtenerViajesDescargaPendiente setKey(java.lang.String key) {
      return (ObtenerViajesDescargaPendiente) super.setKey(key);
    }

    @Override
    public ObtenerViajesDescargaPendiente setOauthToken(java.lang.String oauthToken) {
      return (ObtenerViajesDescargaPendiente) super.setOauthToken(oauthToken);
    }

    @Override
    public ObtenerViajesDescargaPendiente setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ObtenerViajesDescargaPendiente) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ObtenerViajesDescargaPendiente setQuotaUser(java.lang.String quotaUser) {
      return (ObtenerViajesDescargaPendiente) super.setQuotaUser(quotaUser);
    }

    @Override
    public ObtenerViajesDescargaPendiente setUserIp(java.lang.String userIp) {
      return (ObtenerViajesDescargaPendiente) super.setUserIp(userIp);
    }

    @Override
    public ObtenerViajesDescargaPendiente set(String parameterName, Object value) {
      return (ObtenerViajesDescargaPendiente) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "obtenerViajesPendientesDeCobros".
   *
   * This request holds the parameters needed by the viajeendpoint server.  After setting any optional
   * parameters, call the {@link ObtenerViajesPendientesDeCobros#execute()} method to invoke the
   * remote operation.
   *
   * @param cliente
   * @return the request
   */
  public ObtenerViajesPendientesDeCobros obtenerViajesPendientesDeCobros(java.lang.String cliente) throws java.io.IOException {
    ObtenerViajesPendientesDeCobros result = new ObtenerViajesPendientesDeCobros(cliente);
    initialize(result);
    return result;
  }

  public class ObtenerViajesPendientesDeCobros extends ViajeendpointRequest<com.conexion.entidades.viajeendpoint.model.ViajeCollection> {

    private static final String REST_PATH = "obtenerViajesPendientesDeCobros/{cliente}";

    /**
     * Create a request for the method "obtenerViajesPendientesDeCobros".
     *
     * This request holds the parameters needed by the the viajeendpoint server.  After setting any
     * optional parameters, call the {@link ObtenerViajesPendientesDeCobros#execute()} method to
     * invoke the remote operation. <p> {@link ObtenerViajesPendientesDeCobros#initialize(com.google.a
     * pi.client.googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this
     * instance immediately after invoking the constructor. </p>
     *
     * @param cliente
     * @since 1.13
     */
    protected ObtenerViajesPendientesDeCobros(java.lang.String cliente) {
      super(Viajeendpoint.this, "POST", REST_PATH, null, com.conexion.entidades.viajeendpoint.model.ViajeCollection.class);
      this.cliente = com.google.api.client.util.Preconditions.checkNotNull(cliente, "Required parameter cliente must be specified.");
    }

    @Override
    public ObtenerViajesPendientesDeCobros setAlt(java.lang.String alt) {
      return (ObtenerViajesPendientesDeCobros) super.setAlt(alt);
    }

    @Override
    public ObtenerViajesPendientesDeCobros setFields(java.lang.String fields) {
      return (ObtenerViajesPendientesDeCobros) super.setFields(fields);
    }

    @Override
    public ObtenerViajesPendientesDeCobros setKey(java.lang.String key) {
      return (ObtenerViajesPendientesDeCobros) super.setKey(key);
    }

    @Override
    public ObtenerViajesPendientesDeCobros setOauthToken(java.lang.String oauthToken) {
      return (ObtenerViajesPendientesDeCobros) super.setOauthToken(oauthToken);
    }

    @Override
    public ObtenerViajesPendientesDeCobros setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ObtenerViajesPendientesDeCobros) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ObtenerViajesPendientesDeCobros setQuotaUser(java.lang.String quotaUser) {
      return (ObtenerViajesPendientesDeCobros) super.setQuotaUser(quotaUser);
    }

    @Override
    public ObtenerViajesPendientesDeCobros setUserIp(java.lang.String userIp) {
      return (ObtenerViajesPendientesDeCobros) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cliente;

    /**

     */
    public java.lang.String getCliente() {
      return cliente;
    }

    public ObtenerViajesPendientesDeCobros setCliente(java.lang.String cliente) {
      this.cliente = cliente;
      return this;
    }

    @Override
    public ObtenerViajesPendientesDeCobros set(String parameterName, Object value) {
      return (ObtenerViajesPendientesDeCobros) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "obtenerViajesPendientesDePago".
   *
   * This request holds the parameters needed by the viajeendpoint server.  After setting any optional
   * parameters, call the {@link ObtenerViajesPendientesDePago#execute()} method to invoke the remote
   * operation.
   *
   * @param proveedor
   * @return the request
   */
  public ObtenerViajesPendientesDePago obtenerViajesPendientesDePago(java.lang.String proveedor) throws java.io.IOException {
    ObtenerViajesPendientesDePago result = new ObtenerViajesPendientesDePago(proveedor);
    initialize(result);
    return result;
  }

  public class ObtenerViajesPendientesDePago extends ViajeendpointRequest<com.conexion.entidades.viajeendpoint.model.ViajeCollection> {

    private static final String REST_PATH = "obtenerViajesPendientesDePago/{proveedor}";

    /**
     * Create a request for the method "obtenerViajesPendientesDePago".
     *
     * This request holds the parameters needed by the the viajeendpoint server.  After setting any
     * optional parameters, call the {@link ObtenerViajesPendientesDePago#execute()} method to invoke
     * the remote operation. <p> {@link ObtenerViajesPendientesDePago#initialize(com.google.api.client
     * .googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param proveedor
     * @since 1.13
     */
    protected ObtenerViajesPendientesDePago(java.lang.String proveedor) {
      super(Viajeendpoint.this, "POST", REST_PATH, null, com.conexion.entidades.viajeendpoint.model.ViajeCollection.class);
      this.proveedor = com.google.api.client.util.Preconditions.checkNotNull(proveedor, "Required parameter proveedor must be specified.");
    }

    @Override
    public ObtenerViajesPendientesDePago setAlt(java.lang.String alt) {
      return (ObtenerViajesPendientesDePago) super.setAlt(alt);
    }

    @Override
    public ObtenerViajesPendientesDePago setFields(java.lang.String fields) {
      return (ObtenerViajesPendientesDePago) super.setFields(fields);
    }

    @Override
    public ObtenerViajesPendientesDePago setKey(java.lang.String key) {
      return (ObtenerViajesPendientesDePago) super.setKey(key);
    }

    @Override
    public ObtenerViajesPendientesDePago setOauthToken(java.lang.String oauthToken) {
      return (ObtenerViajesPendientesDePago) super.setOauthToken(oauthToken);
    }

    @Override
    public ObtenerViajesPendientesDePago setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ObtenerViajesPendientesDePago) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ObtenerViajesPendientesDePago setQuotaUser(java.lang.String quotaUser) {
      return (ObtenerViajesPendientesDePago) super.setQuotaUser(quotaUser);
    }

    @Override
    public ObtenerViajesPendientesDePago setUserIp(java.lang.String userIp) {
      return (ObtenerViajesPendientesDePago) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String proveedor;

    /**

     */
    public java.lang.String getProveedor() {
      return proveedor;
    }

    public ObtenerViajesPendientesDePago setProveedor(java.lang.String proveedor) {
      this.proveedor = proveedor;
      return this;
    }

    @Override
    public ObtenerViajesPendientesDePago set(String parameterName, Object value) {
      return (ObtenerViajesPendientesDePago) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "obtenerViajesPorFletero".
   *
   * This request holds the parameters needed by the viajeendpoint server.  After setting any optional
   * parameters, call the {@link ObtenerViajesPorFletero#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public ObtenerViajesPorFletero obtenerViajesPorFletero(java.lang.Long id) throws java.io.IOException {
    ObtenerViajesPorFletero result = new ObtenerViajesPorFletero(id);
    initialize(result);
    return result;
  }

  public class ObtenerViajesPorFletero extends ViajeendpointRequest<com.conexion.entidades.viajeendpoint.model.ViajeCollection> {

    private static final String REST_PATH = "obtenerViajesPorFletero/{id}";

    /**
     * Create a request for the method "obtenerViajesPorFletero".
     *
     * This request holds the parameters needed by the the viajeendpoint server.  After setting any
     * optional parameters, call the {@link ObtenerViajesPorFletero#execute()} method to invoke the
     * remote operation. <p> {@link ObtenerViajesPorFletero#initialize(com.google.api.client.googleapi
     * s.services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected ObtenerViajesPorFletero(java.lang.Long id) {
      super(Viajeendpoint.this, "POST", REST_PATH, null, com.conexion.entidades.viajeendpoint.model.ViajeCollection.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public ObtenerViajesPorFletero setAlt(java.lang.String alt) {
      return (ObtenerViajesPorFletero) super.setAlt(alt);
    }

    @Override
    public ObtenerViajesPorFletero setFields(java.lang.String fields) {
      return (ObtenerViajesPorFletero) super.setFields(fields);
    }

    @Override
    public ObtenerViajesPorFletero setKey(java.lang.String key) {
      return (ObtenerViajesPorFletero) super.setKey(key);
    }

    @Override
    public ObtenerViajesPorFletero setOauthToken(java.lang.String oauthToken) {
      return (ObtenerViajesPorFletero) super.setOauthToken(oauthToken);
    }

    @Override
    public ObtenerViajesPorFletero setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ObtenerViajesPorFletero) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ObtenerViajesPorFletero setQuotaUser(java.lang.String quotaUser) {
      return (ObtenerViajesPorFletero) super.setQuotaUser(quotaUser);
    }

    @Override
    public ObtenerViajesPorFletero setUserIp(java.lang.String userIp) {
      return (ObtenerViajesPorFletero) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public ObtenerViajesPorFletero setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public ObtenerViajesPorFletero set(String parameterName, Object value) {
      return (ObtenerViajesPorFletero) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeViaje".
   *
   * This request holds the parameters needed by the viajeendpoint server.  After setting any optional
   * parameters, call the {@link RemoveViaje#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveViaje removeViaje(java.lang.Long id) throws java.io.IOException {
    RemoveViaje result = new RemoveViaje(id);
    initialize(result);
    return result;
  }

  public class RemoveViaje extends ViajeendpointRequest<Void> {

    private static final String REST_PATH = "viaje/{id}";

    /**
     * Create a request for the method "removeViaje".
     *
     * This request holds the parameters needed by the the viajeendpoint server.  After setting any
     * optional parameters, call the {@link RemoveViaje#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveViaje#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveViaje(java.lang.Long id) {
      super(Viajeendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveViaje setAlt(java.lang.String alt) {
      return (RemoveViaje) super.setAlt(alt);
    }

    @Override
    public RemoveViaje setFields(java.lang.String fields) {
      return (RemoveViaje) super.setFields(fields);
    }

    @Override
    public RemoveViaje setKey(java.lang.String key) {
      return (RemoveViaje) super.setKey(key);
    }

    @Override
    public RemoveViaje setOauthToken(java.lang.String oauthToken) {
      return (RemoveViaje) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveViaje setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveViaje) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveViaje setQuotaUser(java.lang.String quotaUser) {
      return (RemoveViaje) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveViaje setUserIp(java.lang.String userIp) {
      return (RemoveViaje) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveViaje setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveViaje set(String parameterName, Object value) {
      return (RemoveViaje) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateViaje".
   *
   * This request holds the parameters needed by the viajeendpoint server.  After setting any optional
   * parameters, call the {@link UpdateViaje#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.conexion.entidades.viajeendpoint.model.Viaje}
   * @return the request
   */
  public UpdateViaje updateViaje(com.conexion.entidades.viajeendpoint.model.Viaje content) throws java.io.IOException {
    UpdateViaje result = new UpdateViaje(content);
    initialize(result);
    return result;
  }

  public class UpdateViaje extends ViajeendpointRequest<com.conexion.entidades.viajeendpoint.model.Viaje> {

    private static final String REST_PATH = "viaje";

    /**
     * Create a request for the method "updateViaje".
     *
     * This request holds the parameters needed by the the viajeendpoint server.  After setting any
     * optional parameters, call the {@link UpdateViaje#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateViaje#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.conexion.entidades.viajeendpoint.model.Viaje}
     * @since 1.13
     */
    protected UpdateViaje(com.conexion.entidades.viajeendpoint.model.Viaje content) {
      super(Viajeendpoint.this, "PUT", REST_PATH, content, com.conexion.entidades.viajeendpoint.model.Viaje.class);
    }

    @Override
    public UpdateViaje setAlt(java.lang.String alt) {
      return (UpdateViaje) super.setAlt(alt);
    }

    @Override
    public UpdateViaje setFields(java.lang.String fields) {
      return (UpdateViaje) super.setFields(fields);
    }

    @Override
    public UpdateViaje setKey(java.lang.String key) {
      return (UpdateViaje) super.setKey(key);
    }

    @Override
    public UpdateViaje setOauthToken(java.lang.String oauthToken) {
      return (UpdateViaje) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateViaje setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateViaje) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateViaje setQuotaUser(java.lang.String quotaUser) {
      return (UpdateViaje) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateViaje setUserIp(java.lang.String userIp) {
      return (UpdateViaje) super.setUserIp(userIp);
    }

    @Override
    public UpdateViaje set(String parameterName, Object value) {
      return (UpdateViaje) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Viajeendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Viajeendpoint}. */
    @Override
    public Viajeendpoint build() {
      return new Viajeendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ViajeendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setViajeendpointRequestInitializer(
        ViajeendpointRequestInitializer viajeendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(viajeendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
