/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-06-26 at 00:09:35 UTC 
 * Modify at your own risk.
 */

package com.conexion.entidades.viajeendpoint.model;

/**
 * Model definition for Viaje.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the viajeendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Viaje extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String cliente;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String facturado;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fecha;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fechaDeCarga;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fechaDeDescarga;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("fechaPagar_origen")
  private java.lang.String fechaPagarOrigen;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("fechaPago_flete")
  private java.lang.String fechaPagoFlete;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("fecha_pago_descargador")
  private java.lang.String fechaPagoDescargador;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long fletero;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float kilos;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String kilosOrigenReales;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("monto_descargador")
  private java.lang.String montoDescargador;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("nombre_descargador")
  private java.lang.String nombreDescargador;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String observaciones;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String pago;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("pago_descargador")
  private java.lang.String pagoDescargador;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("pago_descargados")
  private java.lang.String pagoDescargados;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("pago_flete")
  private java.lang.String pagoFlete;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean pendienteCarga;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean pendienteDeCobro;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean pendienteDeDescarga;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean pendienteDePago;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("precioXtonelada_flete")
  private java.lang.String precioXtoneladaFlete;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("precio_kilo")
  private java.lang.Float precioKilo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String proveedor;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("saldo_descargador")
  private java.lang.String saldoDescargador;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String tipoCarga;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long usuarioResponsable;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCliente() {
    return cliente;
  }

  /**
   * @param cliente cliente or {@code null} for none
   */
  public Viaje setCliente(java.lang.String cliente) {
    this.cliente = cliente;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFacturado() {
    return facturado;
  }

  /**
   * @param facturado facturado or {@code null} for none
   */
  public Viaje setFacturado(java.lang.String facturado) {
    this.facturado = facturado;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFecha() {
    return fecha;
  }

  /**
   * @param fecha fecha or {@code null} for none
   */
  public Viaje setFecha(java.lang.String fecha) {
    this.fecha = fecha;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFechaDeCarga() {
    return fechaDeCarga;
  }

  /**
   * @param fechaDeCarga fechaDeCarga or {@code null} for none
   */
  public Viaje setFechaDeCarga(java.lang.String fechaDeCarga) {
    this.fechaDeCarga = fechaDeCarga;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFechaDeDescarga() {
    return fechaDeDescarga;
  }

  /**
   * @param fechaDeDescarga fechaDeDescarga or {@code null} for none
   */
  public Viaje setFechaDeDescarga(java.lang.String fechaDeDescarga) {
    this.fechaDeDescarga = fechaDeDescarga;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFechaPagarOrigen() {
    return fechaPagarOrigen;
  }

  /**
   * @param fechaPagarOrigen fechaPagarOrigen or {@code null} for none
   */
  public Viaje setFechaPagarOrigen(java.lang.String fechaPagarOrigen) {
    this.fechaPagarOrigen = fechaPagarOrigen;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFechaPagoFlete() {
    return fechaPagoFlete;
  }

  /**
   * @param fechaPagoFlete fechaPagoFlete or {@code null} for none
   */
  public Viaje setFechaPagoFlete(java.lang.String fechaPagoFlete) {
    this.fechaPagoFlete = fechaPagoFlete;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFechaPagoDescargador() {
    return fechaPagoDescargador;
  }

  /**
   * @param fechaPagoDescargador fechaPagoDescargador or {@code null} for none
   */
  public Viaje setFechaPagoDescargador(java.lang.String fechaPagoDescargador) {
    this.fechaPagoDescargador = fechaPagoDescargador;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getFletero() {
    return fletero;
  }

  /**
   * @param fletero fletero or {@code null} for none
   */
  public Viaje setFletero(java.lang.Long fletero) {
    this.fletero = fletero;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Viaje setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getKilos() {
    return kilos;
  }

  /**
   * @param kilos kilos or {@code null} for none
   */
  public Viaje setKilos(java.lang.Float kilos) {
    this.kilos = kilos;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getKilosOrigenReales() {
    return kilosOrigenReales;
  }

  /**
   * @param kilosOrigenReales kilosOrigenReales or {@code null} for none
   */
  public Viaje setKilosOrigenReales(java.lang.String kilosOrigenReales) {
    this.kilosOrigenReales = kilosOrigenReales;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMontoDescargador() {
    return montoDescargador;
  }

  /**
   * @param montoDescargador montoDescargador or {@code null} for none
   */
  public Viaje setMontoDescargador(java.lang.String montoDescargador) {
    this.montoDescargador = montoDescargador;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNombreDescargador() {
    return nombreDescargador;
  }

  /**
   * @param nombreDescargador nombreDescargador or {@code null} for none
   */
  public Viaje setNombreDescargador(java.lang.String nombreDescargador) {
    this.nombreDescargador = nombreDescargador;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getObservaciones() {
    return observaciones;
  }

  /**
   * @param observaciones observaciones or {@code null} for none
   */
  public Viaje setObservaciones(java.lang.String observaciones) {
    this.observaciones = observaciones;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPago() {
    return pago;
  }

  /**
   * @param pago pago or {@code null} for none
   */
  public Viaje setPago(java.lang.String pago) {
    this.pago = pago;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPagoDescargador() {
    return pagoDescargador;
  }

  /**
   * @param pagoDescargador pagoDescargador or {@code null} for none
   */
  public Viaje setPagoDescargador(java.lang.String pagoDescargador) {
    this.pagoDescargador = pagoDescargador;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPagoDescargados() {
    return pagoDescargados;
  }

  /**
   * @param pagoDescargados pagoDescargados or {@code null} for none
   */
  public Viaje setPagoDescargados(java.lang.String pagoDescargados) {
    this.pagoDescargados = pagoDescargados;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPagoFlete() {
    return pagoFlete;
  }

  /**
   * @param pagoFlete pagoFlete or {@code null} for none
   */
  public Viaje setPagoFlete(java.lang.String pagoFlete) {
    this.pagoFlete = pagoFlete;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getPendienteCarga() {
    return pendienteCarga;
  }

  /**
   * @param pendienteCarga pendienteCarga or {@code null} for none
   */
  public Viaje setPendienteCarga(java.lang.Boolean pendienteCarga) {
    this.pendienteCarga = pendienteCarga;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getPendienteDeCobro() {
    return pendienteDeCobro;
  }

  /**
   * @param pendienteDeCobro pendienteDeCobro or {@code null} for none
   */
  public Viaje setPendienteDeCobro(java.lang.Boolean pendienteDeCobro) {
    this.pendienteDeCobro = pendienteDeCobro;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getPendienteDeDescarga() {
    return pendienteDeDescarga;
  }

  /**
   * @param pendienteDeDescarga pendienteDeDescarga or {@code null} for none
   */
  public Viaje setPendienteDeDescarga(java.lang.Boolean pendienteDeDescarga) {
    this.pendienteDeDescarga = pendienteDeDescarga;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getPendienteDePago() {
    return pendienteDePago;
  }

  /**
   * @param pendienteDePago pendienteDePago or {@code null} for none
   */
  public Viaje setPendienteDePago(java.lang.Boolean pendienteDePago) {
    this.pendienteDePago = pendienteDePago;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPrecioXtoneladaFlete() {
    return precioXtoneladaFlete;
  }

  /**
   * @param precioXtoneladaFlete precioXtoneladaFlete or {@code null} for none
   */
  public Viaje setPrecioXtoneladaFlete(java.lang.String precioXtoneladaFlete) {
    this.precioXtoneladaFlete = precioXtoneladaFlete;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getPrecioKilo() {
    return precioKilo;
  }

  /**
   * @param precioKilo precioKilo or {@code null} for none
   */
  public Viaje setPrecioKilo(java.lang.Float precioKilo) {
    this.precioKilo = precioKilo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProveedor() {
    return proveedor;
  }

  /**
   * @param proveedor proveedor or {@code null} for none
   */
  public Viaje setProveedor(java.lang.String proveedor) {
    this.proveedor = proveedor;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSaldoDescargador() {
    return saldoDescargador;
  }

  /**
   * @param saldoDescargador saldoDescargador or {@code null} for none
   */
  public Viaje setSaldoDescargador(java.lang.String saldoDescargador) {
    this.saldoDescargador = saldoDescargador;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTipoCarga() {
    return tipoCarga;
  }

  /**
   * @param tipoCarga tipoCarga or {@code null} for none
   */
  public Viaje setTipoCarga(java.lang.String tipoCarga) {
    this.tipoCarga = tipoCarga;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUsuarioResponsable() {
    return usuarioResponsable;
  }

  /**
   * @param usuarioResponsable usuarioResponsable or {@code null} for none
   */
  public Viaje setUsuarioResponsable(java.lang.Long usuarioResponsable) {
    this.usuarioResponsable = usuarioResponsable;
    return this;
  }

  @Override
  public Viaje set(String fieldName, Object value) {
    return (Viaje) super.set(fieldName, value);
  }

  @Override
  public Viaje clone() {
    return (Viaje) super.clone();
  }

}
